//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZTOA_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obj_File_Relation
    {
        public string TableDesc { get; set; }
        public int FileId { get; set; }
        public string FilePath { get; set; }
        public string OldFileName { get; set; }
        public string FileName { get; set; }
        public long FileSize { get; set; }
        public string FileExtend { get; set; }
    }
}
