//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZTOA_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Info
    {
        public string TableDesc { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UserPhone { get; set; }
        public string UserAccount { get; set; }
        public string UserPwd { get; set; }
        public string UserFaceImgId { get; set; }
        public string UserNation { get; set; }
        public string UserIdCard { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
