//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZTOA_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zztEntities : DbContext
    {
        public zztEntities()
            : base("name=zztEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<From_Control> From_Control { get; set; }
        public virtual DbSet<From_Data> From_Data { get; set; }
        public virtual DbSet<From_Layout> From_Layout { get; set; }
        public virtual DbSet<Group_Info> Group_Info { get; set; }
        public virtual DbSet<Menu_Info> Menu_Info { get; set; }
        public virtual DbSet<Obj_File_Relation> Obj_File_Relation { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User_Info> User_Info { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
    }
}
